from ray.rllib.algorithms.callbacks import DefaultCallbacks
from ray.rllib.algorithms.algorithm import Algorithm
from ray.rllib.algorithms.callbacks import DefaultCallbacks
from ray.rllib.evaluation.episode_v2 import EpisodeV2
from ray.rllib.utils.typing import PolicyID
from ray.rllib.env import BaseEnv
from ray.rllib.evaluation import Episode, RolloutWorker
from ray.rllib.policy import Policy
from ray.rllib.policy.sample_batch import DEFAULT_POLICY_ID, SampleBatch
from typing import Dict, Optional, Union

class TrainingCallbacks(DefaultCallbacks):
    def on_episode_start(self, worker, base_env, policies, episode, **kwargs):
        # pass
        envs = base_env.get_sub_environments()
        for env in envs:
            if env.annealing_reward_shaping:
                env.anneal_reward_shaping_factor(worker.global_vars['timestep'])

        if 'polBREval' in policies and hasattr(policies['polBREval'], 'prev_decodes'):
            policies["polBREval"].prev_decodes = {}
            policies["polBREval"].cumulative_regret = None
            policies["polBREval"].expert_weights = None
            #print("Episode started. Resetting previous decodes, cumulative regret, and expert weights.")

        if hasattr(worker, 'global_eval_vars'):
            if worker.global_eval_vars["flush_all"]:
                #print("Flushed all eval policies once.")
                worker.global_eval_vars["flush_all"] = False
                # NOTE: this is probably redundant but doing just in case
                worker.global_eval_vars["curr_partner_idx"] = 0
 
            if worker.global_eval_vars["env_inc"] == len(envs):
                worker.global_eval_vars["env_inc"] = 0
                worker.global_eval_vars["curr_partner_idx"] = (worker.global_eval_vars["curr_partner_idx"] + 1) % len(worker.global_eval_vars["eval_policies"])
            worker.global_eval_vars["env_inc"] += 1

        super().on_episode_start(worker=worker,base_env=base_env, policies=policies, episode=episode, **kwargs)

    def on_evaluate_start(self, *, algorithm, **kwargs):
        # resets the prev_decodes at the start of every eval ep
        if algorithm.evaluation_workers:
            eval_worker = algorithm.evaluation_workers.local_worker()
            policy = eval_worker.get_policy("polBREval")
            if hasattr(policy, 'prev_decodes'):
                policy.prev_decodes = {}
                #print("Evaluation started. Resetting previous decodes.")
            if hasattr(policy, 'cumulative_regret'):
                policy.cumulative_regret = None
                #print("Evaluation started. Resetting cumulative regret.")
            if hasattr(policy, 'expert_weights'):
                policy.expert_weights = None
                #print("Evaluation started. Resetting expert weights.")

            eval_worker.global_eval_vars = {}
            eval_worker.global_eval_vars["curr_partner_idx"] = 0
            eval_worker.global_eval_vars["flush_all"] = True


    def on_episode_end(self, worker, base_env, policies, episode, **kwargs):
        """
        Used in order to add custom metrics to our tensorboard data

        sparse_reward (int) - total reward from deliveries agent earned this episode
        shaped_reward (int) - total reward shaping reward the agent earned this episode
        """
        # # Get rllib.OvercookedMultiAgentEnv refernce from rllib wraper
        # env = base_env.get_sub_environments()[0]
        # # Both agents share the same info so it doesn't matter whose we use, just use 0th agent's

        info_dict = episode.last_info_for(0)

        ep_info = info_dict["episode"]
        # game_stats = ep_info["ep_game_stats"]

        # # List of episode stats we'd like to collect by agent
        # stats_to_collect = EVENT_TYPES

        # # Parse info dicts generated by OvercookedEnv
        tot_sparse_reward = ep_info["ep_sparse_r"]
        tot_shaped_reward = ep_info["ep_shaped_r"]

        # # Store metrics where they will be visible to rllib for tensorboard logging
        episode.custom_metrics["sparse_reward"] = tot_sparse_reward
        episode.custom_metrics["shaped_reward"] = tot_shaped_reward
        episode.custom_metrics["reward_shaping_factor"] = ep_info["reward_shaping_factor"]
        episode.custom_metrics["dish_delivery"] = ep_info['ep_delivery']
        episode.custom_metrics["correct_dish_delivery"] = ep_info['ep_correct_delivery']
        episode.custom_metrics["in_order_delivery"] = ep_info['ep_in_order_delivery']
        super().on_episode_end(worker=worker,base_env=base_env, policies=policies, episode=episode, **kwargs)

class LoggingCallbacks(TrainingCallbacks):
    def on_episode_end(
        self,
        *,
        worker: RolloutWorker,
        base_env: BaseEnv,
        policies: Dict[str, Policy],
        episode: Episode,
        env_index: int,
        **kwargs
    ):
        super().on_episode_end(worker=worker,base_env=base_env, policies=policies, episode=episode, **kwargs)

    
    def on_episode_start(
        self, 
        *, 
        worker: RolloutWorker, 
        base_env: BaseEnv, 
        policies: Dict[PolicyID, Policy], 
        episode: Episode, 
        **kwargs
    ):
        super().on_episode_start(worker, base_env, policies, episode)
