ACTION_SPACE_VALUE: 27
OBS_SPACE_CHANNEL: 12
N_AGENTS: 2
ACTOR_EMBEDDING_DIM: 200
CRITIC_EMBEDDING_DIM: 200
MODEL_CONFIG:
  custom_model: IPPO_model
  custom_model_config:
    model_type: custom_conv
    input_conv_channels: 12
    actor_output_size: 27
    critic_share_layers: false
    conv_filters:
      - - 16
        - 3
        - 1
        - same
        - default
      - - pool
        - 2
        - 2
        - valid
        - null
      - - 32
        - 2
        - 1
        - valid
        - default
      - - 64
        - 2
        - 1
        - valid
        - default
    actor_layer_sizes:
      - - 200
        - 64
      - - 64
        - 27
    critic_layer_sizes:
      - - 200
        - 64
      - - 64
        - 1
    action_masking: true
ENV_CONFIG:
  restrict_capability: false
  max_steps: 2400
  n_agents: 2
  action_level: high
  layout: open
  reward_shaping_factor: 0.4
  reward_shaping_horizon: 20000000
  use_phi: false
  obs_encoder: lossless
  observation_space:
    type: Dict
    spaces:
      image:
        type: Box
        low: -65535
        high: 65535
        shape:
          - 7
          - 10
          - 12
        dtype: int32
      action_mask:
        type: Box
        low: 0
        high: 1
        shape:
          - 27
        dtype: float32
      action_stats:
        type: Box
        low: 0
        high: 1
        shape:
          - 27
        dtype: float32
      order_list:
        type: Box
        low: 0
        high: 1
        shape:
          - 8
        dtype: int8
  action_space:
    type: Discrete
    n: 27
  rew_shaping_params:
    place_tortilla_on_plate:
      - 0
      - 0
    pickup_dish_from_sink:
      - 0
      - 0
    pickup_chopped_ingredient_from_chopboard:
      - 0
      - 0
    place_ingredient_on_grill:
      - 0
      - 0
    pickup_cooked_ingredient_from_grill:
      - 0
      - 0
    place_ingredient_on_pot:
      - 3
      - 3
    pickup_cooked_ingredient_from_pot:
      - 5
      - 5
    pickup_mushroom:
      - 0
      - 0
    pickup_meat:
      - 0
      - 0
    pickup_rice:
      - 0
      - 0
    extinguish_fire:
      - 1
      - 1
    place_charcoal_on_trash:
      - 1
      - 1
    burn_ingredient: -0.01
    wash_dish:
      - 3
      - 3
    food_assembly:
      - 5
      - 5
    serve_dish:
      - 10
      - 10
    wrong_dish_discount: 1
    correct_dish_bonus: 1
    random_dish_delivery: 0
    multiplier_params:
      - - 1
        - 1
      - - 4
        - 2
      - - 100
        - 5
BASE_CONFIG:
  env: burrito
  count_steps_by: env_steps
  alg: PPO
  sgd_minibatch_size: 512
  num_sgd_iter: 4
  train_batch_size: 8192
  lr_schedule:
    - - 0
      - 0.001
    - - 1000000
      - 0.001
    - - 2500000
      - 0.0001
  lambda: 0.999
  kl_coeff: 0.5
  clip_rewards: false
  clip_param: 0.2
  vf_clip_param: 10
  vf_loss_coeff: 0.5
  entropy_coeff: 0.01
  gamma: 0.999
  rollout_fragment_length: auto
  batch_mode: truncate_episodes
  num_workers: 4
  num_envs_per_worker: 4
  num_cpus_per_worker: 1
  num_cpus_for_driver: 1
  num_gpus: 3
  num_gpus_per_worker: 0
  framework: torch
  use_gae: true
  pretrained_model_path:
    - /data/shuyang/overcooked/src/burrito_rl/policy_params/open_bp_population3/pol10/policy_state.pkl
    - /data/shuyang/overcooked/src/burrito_rl/policy_params/open_bp_population3/polBR10/policy_state.pkl
