ACTION_SPACE_VALUE: &action_space 27
OBS_SPACE_CHANNEL: &obs_channel 12
N_AGENTS: &n_agnets 2
ACTOR_EMBEDDING_DIM: &actor_embedding_dim 424 #776
CRITIC_EMBEDDING_DIM: &critic_embedding_dim 424 #776
CLUSTER_EMBEDDING_DIM: &cluster_embedding_dim 32
N_CLUSTERS: &n_clusters 11

# VAE Configuration
VAE_CONFIG: &vae_config
  vae_path: "/home/gpu01/tianxiaojia/Workplace2/talents-zsc/encoder/15000000/fc_mep/20260612_w_50_h_50_b_0.05"
  gaussians_path: "/home/gpu01/tianxiaojia/Workplace2/talents-zsc/encoder/15000000/fc_mep/20260612_w_50_h_50_b_0.05/kmeans/gaussians.pkl"
  latent_dim: 8
  window_length: 50 #100
  vae_horizon: 50 #1
  action_dim: 27
  obs_shape: [10, 8, *obs_channel]


# Model configuration using cluster conditioning
MODEL_CONFIG:
  custom_model: IPPO_model
  custom_model_config:
    model_type: custom_conv
    input_conv_channels: *obs_channel
    actor_output_size: *action_space
    critic_share_layers: false
    num_clusters: *n_clusters  # Pass number of clusters to model
    conv_filters:
      - - 16
        - 3
        - 1
        - same
        - "default"
      - - "pool"
        - 2
        - 2
        - valid
        - Null
      - - 32
        - 2
        - 1
        - valid
        - "default"
      - - 64
        - 2
        - 1
        - valid
        - "default"
    # Updated layer sizes to account for cluster embedding
    actor_layer_sizes:
      #- - 232 #808  # actor_embedding_dim (768) + order_list (8) + cluster_embedding (32)
      - - 392
        - 64
      - - 64
        - *action_space
    critic_layer_sizes:
      #- - 232 #808  # Same calculation as actor
      - - 392
        - 64
      - - 64
        - 1
    action_masking: true

# Environment configuration
ENV_CONFIG:
  restrict_capability: false
  max_steps: 2400
  n_agents: *n_agnets
  action_level: high
  layout: fc
  reward_shaping_factor: 0
  annealing_reward_shaping: true
  reward_shaping_horizon: 25000000
  use_phi: false
  obs_encoder: lossless
  cluster_br: True
  num_clusters: *n_clusters
  observation_space:
    type: Dict
    spaces:
      image:
        type: Box
        low: -65535
        high: 65535
        shape: [10, 8, *obs_channel]
        dtype: int32
      action_mask:
        type: Box
        low: 0
        high: 1
        shape:
          - *action_space
        dtype: float32
      action_stats:
        type: Box
        low: 0
        high: 1
        shape:
          - *action_space
        dtype: float32
      order_list:
        type: Box
        low: 0
        high: 1
        shape:
          - 8
        dtype: int8
      cluster_id:  # Add field for cluster_id 
        type: Box
        low: 0
        high: 1
        shape:
          - *n_clusters
        dtype: int8
      prev_action:
        type: Box
        low: 0
        high: 8
        shape:
          - *action_space
        dtype: float32
  action_space:
    type: Discrete
    n: *action_space
  rew_shaping_params:
    # Same reward shaping parameters as before
    place_tortilla_on_plate: [2,2]
    pickup_dish_from_sink: [3,3]
    pickup_chopped_ingredient_from_chopboard: [2,2]
    place_ingredient_on_grill: [2,2]
    pickup_cooked_ingredient_from_grill: [4,4]
    place_ingredient_on_pot: [2,2]
    pickup_cooked_ingredient_from_pot: [4,4]
    chop_ingredient: [1,1]
    pickup_mushroom: [0,0]
    pickup_meat: [0,0]
    pickup_rice: [0,0]
    pickup_tortilla: [0,0]
    extinguish_fire: [0,0]
    place_charcoal_on_trash: [0,0]
    burn_ingredient: -0.0
    wash_dish: [1,1]
    food_assembly: [5,5]
    serve_dish: [10,10]
    wrong_dish_discount: 1
    correct_dish_bonus: 1
    random_dish_delivery: 0
    multiplier_params: [[1,1], [4,2], [100,5]]

# Base configuration
BASE_CONFIG:
  env: burrito
  count_steps_by: env_steps
  alg: "VAEBR"  # Changed from BR to VAEBR
  n_clusters: *n_clusters  # Set number of clusters
  sgd_minibatch_size: 768
  num_sgd_iter: 4
  train_batch_size: 38400
  lr_schedule: [[0, 0.001], [8000000, 0.001], [16000000, 0.0001]]
  lambda: 0.99
  kl_coeff: 0.5
  clip_rewards: false
  clip_param: 0.2
  vf_clip_param: 10
  vf_loss_coeff: 0.5
  entropy_coeff: 0.02
  grad_clip: 1.0
  gamma: 0.995
  rollout_fragment_length: auto
  batch_mode: truncate_episodes
  num_workers: 8
  num_envs_per_worker: 4
  num_cpus_per_worker: 1
  num_cpus_for_driver: 8
  num_gpus: 1
  num_gpus_per_worker: 0
  framework: torch
  use_gae: true
  partner_sampling_method: priority
  num_history: 10
 
  custom_eval: True

  learning_rate: 0.2
  alpha: 0.4
  decay_factor: 1

  evaluation_interval: 100
  pretrained_model_dir: /home/gpu01/tianxiaojia/Workplace2/talents-zsc/overcooked/src/burrito_rl/policy_params/fc_pp_mep_15000000/0000/checkpoint_000000
  pretrained_model_paths:
    - 101
    - 102
    - 111
    - 112
    - 121
    - 122
  
  # Include VAE configuration
  <<: *vae_config
